version: "3.8"

services:
  mongodb:
    image: mongo:6.0.4
    container_name: mongodb
    ports:
      - "27017:27017"
    healthcheck:
      test: echo 'db.stats().ok' | mongosh localhost:27017/moviesdb --quiet
    security_opt:
      - no-new-privileges:true

  postgres:
    image: postgres:15.2
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: "pg_isready -U postgres"
    security_opt:
      - no-new-privileges:true

  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL_HOST=postgres
      - KC_DB_URL_DATABASE=keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=password
      - KC_HEALTH_ENABLED=true
    ports:
      - "8080:8080"
    command: start-dev
    depends_on:
      - postgres
    healthcheck:
      test: "curl -f http://localhost:8080/health/ready || exit 1"
    security_opt:
      - no-new-privileges:true
    read_only: true

  dependency-track:
    image: owasp/dependency-track
    container_name: dependency-track
    ports:
      - "9082:9080"
    environment:
      - DB_CONNECTION_STRING=jdbc:postgresql://postgres:5432/dependencytrack
      - DB_USERNAME=dependencytrack
      - DB_PASSWORD=password
    depends_on:
      - postgres
    healthcheck:
      test: "curl -f http://localhost:8082/api/v1/health || exit 1"
    security_opt:
      - no-new-privileges:true
    read_only: true
